# Generated by Django 4.2.13 on 2025-01-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('body_text', models.TextField()),
                ('preview', models.ImageField(upload_to='')),
                ('video_link', models.CharField(max_length=255)),
            ],
        ),
    ]
