# Generated by Django 4.2.13 on 2025-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officeAddress', models.CharField(max_length=255)),
                ('factoryAddress', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=255)),
            ],
        ),
    ]
