# Generated by Django 5.2 on 2026-06-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='body_text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='body_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='body_text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='category_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
