# Generated by Django 5.2 on 2026-06-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_subtitle_alter_project_body_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
