# Generated by Django 5.2 on 2026-06-05 14:14

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_subtitle_en_project_subtitle_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body_text',
            field=ckeditor.fields.RichTextField(verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_text_en',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_text_ru',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_text_uz',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle_en',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subtitle_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category_name',
            field=models.CharField(max_length=255, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='category_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
