# Generated by Django 5.2 on 2026-07-07 08:29

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_category_alter_project_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='projects/images/', verbose_name='Image'),
        ),
    ]
