# Generated by Django 5.2 on 2026-07-07 11:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projectimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body_text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
    ]
