# Generated by Django 4.2.13 on 2025-01-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
