# Generated by Django 5.2.1 on 2025-06-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newscategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
