# Generated by Django 5.2.1 on 2025-06-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='body_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NewsText',
        ),
    ]
