# Generated by Django 4.2.23 on 2025-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_newsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscategory',
            name='category_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='category_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='category_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
