# Generated by Django 5.2 on 2026-06-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newscategory_category_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='news_title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='body_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='body_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsimage',
            name='body_text_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
