# Generated by Django 5.2 on 2026-06-21 18:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_news_news_title_en_news_news_title_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
