# Generated by Django 5.2 on 2026-06-21 18:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_newsimage_body_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='body_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
