# Generated by Django 5.2 on 2026-07-07 08:29

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_newsimage_body_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='news/previews/', verbose_name='Preview Image'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='news/images/', verbose_name='Image'),
        ),
    ]
