# Generated by Django 5.2 on 2026-07-14 16:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_preview_alter_newsimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='body_text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='body_text_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Body Text'),
        ),
    ]
