# Generated by Django 5.2 on 2026-07-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_alter_newsimage_body_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
