# Generated by Django 4.2.13 on 2024-12-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sub_title',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
