# Generated by Django 4.2.13 on 2025-01-24 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_sub_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='advantages',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ProductsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_images', to='products.products')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_advantages', to='products.products')),
            ],
        ),
    ]
