# Generated by Django 4.2.13 on 2025-01-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_products_advantages_productsimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsadvantage',
            name='advtantage',
            field=models.TextField(null=True),
        ),
    ]
