# Generated by Django 4.2.13 on 2025-01-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productsadvantage_advtantage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsadvantage',
            old_name='advtantage',
            new_name='advantage',
        ),
    ]
