# Generated by Django 4.2.13 on 2025-01-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_advtantage_productsadvantage_advantage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq', models.TextField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='products.products')),
            ],
        ),
    ]
