# Generated by Django 4.2.13 on 2025-01-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productsfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsfaq',
            name='answer',
            field=models.TextField(null=True),
        ),
    ]
