# Generated by Django 4.2.13 on 2025-01-31 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productsfaq_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsDescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decription_images', to='products.products')),
            ],
        ),
    ]
