# Generated by Django 4.2.13 on 2025-04-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_second_category_products_second_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='second_category',
        ),
        migrations.RemoveField(
            model_name='second_category',
            name='category',
        ),
        migrations.AddField(
            model_name='second_category',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_category', to='products.products'),
        ),
    ]
