# Generated by Django 4.2.23 on 2025-08-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='advantages_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='advantages_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='advantages_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_title_en',
            field=models.CharField(default='default', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_title_ru',
            field=models.CharField(default='default', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_title_uz',
            field=models.CharField(default='default', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productsadvantage',
            name='advantage_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsadvantage',
            name='advantage_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsadvantage',
            name='advantage_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsfaq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsfaq',
            name='answer_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsfaq',
            name='answer_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsfaq',
            name='faq_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsfaq',
            name='faq_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='productsfaq',
            name='faq_uz',
            field=models.TextField(null=True),
        ),
    ]
