# Generated by Django 4.2.23 on 2026-02-03 15:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_categories_slug_type_category_type_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='doc_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1200, 900], upload_to='products/webp/'),
        ),
        migrations.AlterField(
            model_name='productsimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1200, 900], upload_to='products/webp/'),
        ),
    ]
