# Generated by Django 4.2.23 on 2026-03-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_products_doc_img_alter_productsimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='second_category',
            name='second_category_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='second_category',
            name='second_category_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='second_category',
            name='second_category_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='product_type_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='product_type_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='product_type_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
