# Generated by Django 4.2.23 on 2026-03-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_second_category_second_category_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
