# Generated by Django 4.2.23 on 2026-03-15 15:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_products_sub_title_alter_products_sub_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage_uz',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
