# Generated by Django 4.2.23 on 2026-03-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_productsadvantage_advantage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='payment_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='products',
            name='payment_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='products',
            name='payment_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Payment'),
        ),
        migrations.AddField(
            model_name='products',
            name='warranty_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Warranty'),
        ),
        migrations.AddField(
            model_name='products',
            name='warranty_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Warranty'),
        ),
        migrations.AddField(
            model_name='products',
            name='warranty_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Warranty'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='products',
            name='advantages',
            field=models.TextField(null=True, verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='advantages_en',
            field=models.TextField(null=True, verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='advantages_ru',
            field=models.TextField(null=True, verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='advantages_uz',
            field=models.TextField(null=True, verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.brand', verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='certificate',
            field=models.CharField(max_length=255, verbose_name='Certificate'),
        ),
        migrations.AlterField(
            model_name='products',
            name='dimensions',
            field=models.CharField(max_length=255, verbose_name='Dimensions'),
        ),
        migrations.AlterField(
            model_name='products',
            name='max_power',
            field=models.CharField(max_length=255, verbose_name='Maximum Power'),
        ),
        migrations.AlterField(
            model_name='products',
            name='payment',
            field=models.CharField(max_length=255, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_model',
            field=models.CharField(max_length=255, verbose_name='Product Model'),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.type', verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_title_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub Title'),
        ),
        migrations.AlterField(
            model_name='products',
            name='warranty',
            field=models.CharField(max_length=255, verbose_name='Warranty'),
        ),
        migrations.AlterField(
            model_name='type',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='products.categories', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product_type',
            field=models.CharField(max_length=255, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product_type_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product_type_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='product_type_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
