# Generated by Django 4.2.23 on 2026-03-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_products_payment_en_products_payment_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='categories',
            name='category_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Category'),
        ),
    ]
