# Generated by Django 5.2 on 2026-07-02 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_categories_category_en_categories_category_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='second_category',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductsFAQ',
        ),
        migrations.DeleteModel(
            name='Second_Category',
        ),
    ]
