# Generated by Django 5.2 on 2026-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_remove_second_category_product_delete_productsfaq_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='advantages',
            field=models.TextField(blank=True, null=True, verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='advantages_en',
            field=models.TextField(blank=True, null=True, verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='advantages_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Advantages'),
        ),
        migrations.AlterField(
            model_name='products',
            name='advantages_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Advantages'),
        ),
    ]
