# Generated by Django 5.2 on 2026-07-02 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_alter_products_advantages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsadvantage',
            name='advantage_uz',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
